
CREATE TABLE brand (
    ID_BRAND INT PRIMARY KEY,
    NAMA_BRAND VARCHAR(100) UNIQUE
);

CREATE TABLE phones (
    ID_PHONE INT PRIMARY KEY,
    ID_BRAND INT,
    NAMA_HANDPHONE VARCHAR(100) UNIQUE,
    DESKRIPSI VARCHAR(255),
    HARGA INT,
    STOK INT
);

CREATE TABLE users (
    ID_USER INT PRIMARY KEY,
    NAMA_LENGKAP VARCHAR(100) NOT NULL,
    GENDER VARCHAR(100) NOT NULL,
    ALAMAT VARCHAR(255),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TIPE_AKUN VARCHAR(10),
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100)
);

CREATE TABLE session_data (
    ID_USER INT
);

CREATE TABLE transaksi (
    ID_TRANSAKSI INT PRIMARY KEY,
    ID_USER INT,
    NAMA_PELANGGAN VARCHAR(100),
    TANGGAL TIMESTAMP,
    TOTAL_BAYAR INT
);

CREATE TABLE barang_keluar (
    ID_TRANSAKSI INT,
    ID_PHONE INT,
    JUMLAH_KELUAR INT
);


--
--  ALTER TABLE FOR FOREIGN KEY
--

ALTER TABLE phones
  ADD FOREIGN KEY (ID_BRAND) REFERENCES brand (ID_BRAND);


ALTER TABLE transaksi
  ADD FOREIGN KEY (ID_USER) REFERENCES users (ID_USER);


ALTER TABLE session_data
  ADD FOREIGN KEY (ID_USER) REFERENCES users (ID_USER);


ALTER TABLE barang_keluar
    ADD FOREIGN KEY (ID_PHONE) REFERENCES phones (ID_PHONE);


ALTER TABLE barang_keluar
    ADD FOREIGN KEY (ID_TRANSAKSI) REFERENCES transaksi (ID_TRANSAKSI);


--
--  SEQUENCE FOR AUTO INCREMENT
--

CREATE SEQUENCE sequence_brand
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;


CREATE SEQUENCE sequence_phones
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;


CREATE SEQUENCE sequence_users
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;


CREATE SEQUENCE sequence_transaksi
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;


---------------------------
--        TRIGGER        --
---------------------------

CREATE OR REPLACE TRIGGER autoincrement_brand
BEFORE INSERT ON brand
FOR EACH ROW
BEGIN
    SELECT sequence_brand.NEXTVAL
    INTO :new.id_brand
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER autoincrement_phones
BEFORE INSERT ON phones
FOR EACH ROW
BEGIN
    SELECT sequence_phones.NEXTVAL
    INTO :new.ID_PHONE
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER autoincrement_users
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
    SELECT sequence_users.NEXTVAL
    INTO :new.id_user
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER autoincrement_transaksi
BEFORE INSERT ON transaksi
FOR EACH ROW
BEGIN
    SELECT sequence_transaksi.NEXTVAL
    INTO :new.id_transaksi
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER auto_isi_id_transaksi
BEFORE INSERT ON barang_keluar
FOR EACH ROW
BEGIN
    SELECT MAX(ID_TRANSAKSI) 
    INTO :NEW.ID_TRANSAKSI
    FROM transaksi;
END;
/


---------------------------
--       FUNCTION        --
---------------------------

CREATE OR REPLACE FUNCTION getMaxTransaksiId 
RETURN INT
AS
    maxTransaksiId INT;
BEGIN
    SELECT MAX(ID_TRANSAKSI) 
    INTO maxTransaksiId 
    FROM TRANSAKSI;
    
    return maxTransaksiId;
END;
/

CREATE OR REPLACE FUNCTION getMaxBrandId 
RETURN INT
AS
    maxBrandId INT;
BEGIN
    SELECT MAX(ID_BRAND) 
    INTO maxBrandId
    FROM BRAND;
    
    RETURN maxBrandId;
END;
/


---------------------------
--       PROCEDURE       --
---------------------------

CREATE OR REPLACE PROCEDURE insertBrand(
    namaBrand IN VARCHAR2
)
AS
BEGIN
    INSERT INTO BRAND (NAMA_BRAND) 
    VALUES (namaBrand);
END;
/

CREATE OR REPLACE PROCEDURE updateBrand(
    idBrand IN INT,
    namaBrand IN VARCHAR2
)
AS
BEGIN
    UPDATE BRAND 
    SET NAMA_BRAND = namaBrand 
    WHERE ID_BRAND = idBrand;
END;
/

CREATE OR REPLACE PROCEDURE deleteBrand (
    idBrand IN INT
)
AS
BEGIN
    DELETE FROM BRAND 
    WHERE ID_BRAND = idBrand;
END;
/

COMMIT;

---------------------------
--          RUN          --
---------------------------

-- FUNCTION
SELECT getMaxTransaksiId FROM DUAL;
SELECT getMaxBrandId FROM DUAL;

-- PROCEDURE
BEGIN
    insertBrand();
END;

BEGIN
    updatebrand();
END;

BEGIN
    deletebrand();
END;


DROP SEQUENCE SEQUENCE_BRAND;
DROP SEQUENCE SEQUENCE_PHONES;
DROP SEQUENCE SEQUENCE_USERS;
DROP SEQUENCE SEQUENCE_TRANSAKSI;

DROP TABLE BRAND;
DROP TABLE PHONES;
DROP TABLE USERS;
DROP TABLE TRANSAKSI;
DROP TABLE SESSION_DATA;
DROP TABLE BARANG_KELUAR;

SELECT * FROM BRAND;
SELECT * FROM PHONES;
SELECT * FROM USERS;
SELECT * FROM SESSION_DATA;
SELECT * FROM TRANSAKSI;
SELECT * FROM BARANG_KELUAR;

DELETE FROM BRAND;
DELETE FROM PHONES;
DELETE FROM USERS;
DELETE FROM SESSION_DATA;
DELETE FROM BARANG_KELUAR;
DELETE FROM TRANSAKSI;

INSERT INTO users (NAMA_LENGKAP, GENDER, ALAMAT, EMAIL, TIPE_AKUN, USERNAME, PASSWORD) VALUES 
    ('Admin', 'Laki-laki', 'Rungkut, Surabaya', 'admin@gmail.com', 'Admin', 'admin', 'admin');
INSERT INTO users (NAMA_LENGKAP, GENDER, ALAMAT, EMAIL, TIPE_AKUN, USERNAME, PASSWORD) VALUES 
    ('John Doe', 'Male', '123 Main St', 'john.doe@email.com', 'Karyawan', 'john_doe', 'password123');
INSERT INTO users (NAMA_LENGKAP, GENDER, ALAMAT, EMAIL, TIPE_AKUN, USERNAME, PASSWORD) VALUES 
    ('Jane Smith', 'Female', '456 Oak St', 'jane.smith@email.com', 'Karyawan', 'jane_smith', 'securepass');
INSERT INTO users (NAMA_LENGKAP, GENDER, ALAMAT, EMAIL, TIPE_AKUN, USERNAME, PASSWORD) VALUES 
    ('Bob Johnson', 'Male', '789 Pine St', 'bob.johnson@email.com', 'Karyawan', 'bob_johnson', 'pass123');
INSERT INTO users (NAMA_LENGKAP, GENDER, ALAMAT, EMAIL, TIPE_AKUN, USERNAME, PASSWORD) VALUES 
    ('Alice Brown', 'Female', '101 Elm St', 'alice.brown@email.com', 'Karyawan', 'alice_brown', 'strongpassword');

INSERT INTO BRAND (NAMA_BRAND)VALUES ('Samsung');
INSERT INTO BRAND (NAMA_BRAND)VALUES ('Xiaomi');
INSERT INTO BRAND (NAMA_BRAND)VALUES ('Sony');
INSERT INTO BRAND (NAMA_BRAND)VALUES ('Apple');
INSERT INTO BRAND (NAMA_BRAND)VALUES ('Oppo');
INSERT INTO BRAND (NAMA_BRAND)VALUES ('Vivo');

INSERT INTO PHONES (ID_BRAND, NAMA_HANDPHONE, DESKRIPSI, HARGA, STOK) VALUES ('1', 'S23', 'Samsung', '10000', '10');
INSERT INTO PHONES (ID_BRAND, NAMA_HANDPHONE, DESKRIPSI, HARGA, STOK) VALUES ('2', 'POCO X5', 'POCO', '20000', '8');
INSERT INTO PHONES (ID_BRAND, NAMA_HANDPHONE, DESKRIPSI, HARGA, STOK) VALUES ('3', 'Xperia 5', 'Xperia', '30000', '14');
INSERT INTO PHONES (ID_BRAND, NAMA_HANDPHONE, DESKRIPSI, HARGA, STOK) VALUES ('4', 'Iphone 15', 'Iphone','10000', '10');
INSERT INTO PHONES (ID_BRAND, NAMA_HANDPHONE, DESKRIPSI, HARGA, STOK) VALUES ('2', 'POCO M5', 'POCO','20000', '8');
INSERT INTO PHONES (ID_BRAND, NAMA_HANDPHONE, DESKRIPSI, HARGA, STOK) VALUES ('6', 'V70', 'Vivo','30000', '14');

INSERT INTO TRANSAKSI (ID_USER, NAMA_PELANGGAN, TANGGAL, TOTAL_BAYAR) VALUES 
    (1, 'Budi', TO_TIMESTAMP('15-11-2023 12:00:00', 'DD-MM-YYYY HH24:MI:SS'), 20000);
INSERT INTO BARANG_KELUAR (ID_PHONE, JUMLAH_KELUAR) VALUES (1, 4);

INSERT INTO TRANSAKSI (ID_USER, NAMA_PELANGGAN, TANGGAL, TOTAL_BAYAR) VALUES 
    (1, 'Hanzo', TO_TIMESTAMP('15-11-2023 12:00:00', 'DD-MM-YYYY HH24:MI:SS'), 30000);
INSERT INTO BARANG_KELUAR (ID_PHONE, JUMLAH_KELUAR) VALUES (2, 7);

INSERT INTO TRANSAKSI (ID_USER, NAMA_PELANGGAN, TANGGAL, TOTAL_BAYAR) VALUES 
    (1, 'Nana', TO_TIMESTAMP('15-11-2023 12:00:00', 'DD-MM-YYYY HH24:MI:SS'), 10000);
INSERT INTO BARANG_KELUAR (ID_PHONE, JUMLAH_KELUAR) VALUES (3, 2);

INSERT INTO TRANSAKSI (ID_USER, NAMA_PELANGGAN, TANGGAL, TOTAL_BAYAR) VALUES 
    (1, 'Johnson', TO_TIMESTAMP('15-11-2023 12:00:00', 'DD-MM-YYYY HH24:MI:SS'), 50000);
INSERT INTO BARANG_KELUAR (ID_PHONE, JUMLAH_KELUAR) VALUES (4, 10);

INSERT INTO TRANSAKSI (ID_USER, NAMA_PELANGGAN, TANGGAL, TOTAL_BAYAR) VALUES 
    (1, 'Chou', TO_TIMESTAMP('15-11-2023 12:00:00', 'DD-MM-YYYY HH24:MI:SS'), 40000);
INSERT INTO BARANG_KELUAR (ID_PHONE, JUMLAH_KELUAR) VALUES (6, 8);

SELECT 
    T.ID_TRANSAKSI, 
    USR.NAMA_LENGKAP, 
    T.NAMA_PELANGGAN, 
    T.TANGGAL, 
    BR.NAMA_BRAND, 
    PH.NAMA_HANDPHONE, 
    PH.HARGA, 
    BK.JUMLAH_KELUAR, 
    SUM(PH.HARGA * BK.JUMLAH_KELUAR) AS SUBTOTAL,
    T.TOTAL_BAYAR 
FROM TRANSAKSI T 
JOIN BARANG_KELUAR BK ON T.ID_TRANSAKSI = BK.ID_TRANSAKSI 
JOIN USERS USR ON T.ID_USER = USR.ID_USER 
JOIN PHONES PH ON BK.ID_PHONE = PH.ID_PHONE 
JOIN BRAND BR ON PH.ID_BRAND = BR.ID_BRAND 
GROUP BY 
    T.ID_TRANSAKSI, 
    USR.NAMA_LENGKAP, 
    T.NAMA_PELANGGAN, 
    T.TANGGAL, 
    BR.NAMA_BRAND, 
    PH.NAMA_HANDPHONE, 
    PH.HARGA, 
    BK.JUMLAH_KELUAR, 
    T.TOTAL_BAYAR;

