
CREATE TABLE brand (
  ID_BRAND INT PRIMARY KEY,
  NAMA_BRAND VARCHAR(100) UNIQUE
);

CREATE TABLE phones (
  ID_PHONE INT PRIMARY KEY,
  ID_BRAND INT,
  NAMA_HANDPHONE VARCHAR(100) UNIQUE,
  DESKRIPSI VARCHAR(255),
  HARGA INT,
  STOK INT
);

CREATE TABLE users (
  ID_USER INT PRIMARY KEY,
  NAMA_LENGKAP VARCHAR(100) NOT NULL,
  GENDER VARCHAR(100) NOT NULL,
  ALAMAT VARCHAR(255),
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  TIPE_AKUN VARCHAR(10),
  USERNAME VARCHAR(100),
  PASSWORD VARCHAR(100)
);

CREATE TABLE session_data (
  ID_USER INT
);

CREATE TABLE transaksi (
  ID_TRANSAKSI INT PRIMARY KEY,
  ID_USER INT,
  ID_PHONE INT,
  NAMA_PELANGGAN VARCHAR(100),
  TANGGAL TIMESTAMP,
  JUMLAH_BELI INT,
  TOTAL_BAYAR INT
);


//
//  ALTER TABLE FOR FOREIGN KEY
//

ALTER TABLE phones
  ADD FOREIGN KEY (ID_BRAND) REFERENCES brand (ID_BRAND);

ALTER TABLE session_data
  ADD FOREIGN KEY (ID_USER) REFERENCES users (ID_USER);

ALTER TABLE transaksi
  ADD FOREIGN KEY (ID_USER) REFERENCES users (ID_USER);

ALTER TABLE transaksi
  ADD FOREIGN KEY (ID_PHONE) REFERENCES phones (ID_PHONE);


//
//  SEQUENCE FOR AUTO INCREMENT
//

CREATE SEQUENCE sequence_brand
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE sequence_phones
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE sequence_users
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE sequence_transaksi
    START WITH 1
    INCREMENT BY 1
NOMAXVALUE;


//
//  TRIGGER FOR AUTO INCREMENT
//

CREATE OR REPLACE TRIGGER autoincrement_brand
BEFORE INSERT ON brand
FOR EACH ROW
BEGIN
    SELECT sequence_brand.NEXTVAL
    INTO :new.id_brand
    FROM dual;
END;

CREATE OR REPLACE TRIGGER autoincrement_phones
BEFORE INSERT ON phones
FOR EACH ROW
BEGIN
    SELECT sequence_phones.NEXTVAL
    INTO :new.ID_PHONE
    FROM dual;
END;

CREATE OR REPLACE TRIGGER autoincrement_users
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
    SELECT sequence_users.NEXTVAL
    INTO :new.id_user
    FROM dual;
END;

CREATE OR REPLACE TRIGGER autoincrement_transaksi
BEFORE INSERT ON transaksi
FOR EACH ROW
BEGIN
    SELECT sequence_transaksi.NEXTVAL
    INTO :new.id_transaksi
    FROM dual;
END;


COMMIT;

DROP SEQUENCE SEQUENCE_BRAND;
DROP SEQUENCE SEQUENCE_PHONES;
DROP SEQUENCE SEQUENCE_USERS;
DROP SEQUENCE SEQUENCE_TRANSAKSI;

DROP TABLE BRAND;
DROP TABLE PHONES;
DROP TABLE USERS;
DROP TABLE TRANSAKSI;
DROP TABLE SESSION_DATA;

INSERT INTO users (NAMA_LENGKAP, GENDER, ALAMAT, EMAIL, TIPE_AKUN, USERNAME, PASSWORD) VALUES (
'Admin',
'Laki-laki',
'Rungkut, Surabaya',
'admin@gmail.com',
'Admin',
'admin',
'admin');

